### PR TITLE
snapd: bugfix: Fix formatting error and change to critical

### LINKED ISSUE #4636: snapd: Confinement warning not shown when launching a snap from the GUI
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

When launching any snap from the KDE app menu, no confinement warning is shown

### Steps to reproduce

1. Launch any snap (such as Spotify)
2. Look for a pop up notification

### Expected result

A pop up with the confinement warning

### Actual result

No notification is seen

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.6
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.5-311.current (64-bit)
Graphics Platform: Wayland

### Other comments

The functionality was introduced in [this PR](https://github.com/getsolus/packages/pull/3211)
I asked and verified that the GUI notification had not been tested
I exercised it while testing [a more recent PR](https://github.com/getsolus/packages/pull/4632) that updated the wording

The notification mechanism is `nottify-send`. I verified that invoking that on command line does show a notification on my system

The invocation of notify-send seems to be the problem. Trying this manually on command line gets:

```
❯ notify-send \
          --app-name Snap \
          --urgency normal \
          --icon dialog-warning \
          "Snap has ${CONFINEMENT} confinement" \
          "Snaps will stop working in early January 2025." \
          "See ${URL} for details."
Invalid number of options.
```

Three text lines is one too many.

### PR DESCRIPTION
**Pull request by TraceyC77**
**Summary**
Fix text to be two lines not three per spec
Change urgency to critical so users must manually dismiss the notification to give them time to copy the link

Resolves #4636

**Test Plan**

Ran the Spotify and Termius snaps from command line and App menu
Verified the correct warning appeared

**Checklist**

- [x] Package was built and tested against unstable
- [ ] This change could gainfully be listed in the weekly sync notes once merged

### CODE REVIEW

File: packages/s/snapd/files/wrapper.sh [hunk 1]
```diff
@@ -29,15 +29,18 @@ fi
...
       notify-send \
           --app-name Snap \
-          --urgency normal \
+          --urgency critical \
           --icon dialog-warning \
           "Snap has ${CONFINEMENT} confinement" \
-          "Snaps will stop working in early January 2025." \
-          "See ${URL} for details."
+          "Snaps will stop working in early January 2025. For details see<br> \
+          ${URL}"
```
Comment (silkeh) [inline packages/s/snapd/files/wrapper.sh:43]: This doesn't work for me:

image

It also overflows the regular notification:

image

Maybe trim it down so at least `help.getsol.us` is visible:

```suggestion
          "Snaps will stop working in early January 2025. See ${URL}"
```

File: packages/s/snapd/files/wrapper.sh [hunk 2]
```diff
@@ -29,15 +29,18 @@ fi
 
 if [[ "${CONFINEMENT}" != "strict" ]] && [[ "${DISABLE_CONFINEMENT_WARNING:-n}" != "y" ]]
   then
-  if [[ -n "${BAMF_DESKTOP_FILE_HINT+x}" ]] && [[ -n "${GIO_LAUNCHED_DESKTOP_FILE+x}" ]]
+  # This prevents the warning from showing on KDE Plasma
+  # if [[ -n "${BAMF_DESKTOP_FILE_HINT+x}" ]] && [[ -n "${GIO_LAUNCHED_DESKTOP_FILE+x}" ]]
+
```
Comment (silkeh) [inline packages/s/snapd/files/wrapper.sh:34]: I would just remove this entirely if it doesn't work.

```suggestion
```

**Review by silkeh — CHANGES_REQUESTED** [review]

File: packages/s/snapd/files/wrapper.sh (hunk 2 above)
Comment (TraceyC77) [reply packages/s/snapd/files/wrapper.sh:34]: Removed

File: packages/s/snapd/files/wrapper.sh (hunk 1 above)
Comment (TraceyC77) [reply packages/s/snapd/files/wrapper.sh:43]: Well, that lack of ability to translate the br tag is disappointing. My bad for not testing on the other DEs.
I've trimmed down the message and removed the tag.
I tested on Plasma, Budgie and gnome. It looks good on those.
Sadly, my XFCE VM seems to have died after updates.

If you still see an overflow, let me know what DE it's in.

**Review by silkeh — APPROVED** [review]
LGTM, thanks!
